version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'dev'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/Paris'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - 'dependencies'
      - 'automated'
    groups:
      all-dependencies:
        patterns:
          - '*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'dev'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/Paris'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'ci(deps)'
    labels:
      - 'ci'
      - 'dependencies'
      - 'automated'
    groups:
      all-actions:
        patterns:
          - '*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
